'use strict'

global.PRIORITIES_DEFAULT = 6;

global.PRIORITIES_CREEP_DEFAULT = 4;
global.PRIORITIES_CREEP_UPGRADER = 6;
global.PRIORITIES_FORTIFY = 6;
global.PRIORITIES_MINE = 6;

global.PRIORITIES_SPAWNS = 3;
global.PRIORITIES_DEFENSE = 3;

global.PRIORITIES_CITY = 8

global.MINERALS_EXTRACTABLE = [
    RESOURCE_HYDROGEN,
    RESOURCE_OXYGEN,
    RESOURCE_UTRIUM,
    RESOURCE_LEMERGIUM,
    RESOURCE_KEANIUM,
    RESOURCE_ZYNTHIUM,
    RESOURCE_CATALYST
];
